### ISSUE TITLE
Having trouble with eula.txt

### ISSUE THREAD

**Issue by Proofr** [CaenJones/EaglercraftX-Server#4]
In the eula.txt, it contains

eula=true

And in the terminal it says i didnt agree.

**Comment by cyberslash128** [comment]
did you do the eula.txt in bungee or misc?

**Comment by eaglercrack** [comment]
bungee or misc folder? i dont see one in there

**Comment by cyberslash128** [comment]
sry, `server > run server.jar > edit eula.txt > rerun server.jar`

**Comment by eaglercrack** [comment]
edit to what?

**Comment by cyberslash128** [comment]
eula=true

**Comment by Proofr** [comment]
i did and it still do
